export default {
    call_boarding: require('../assets/images/call_boarding.png'),
    bg_boarding: require('../assets/images/bg_boarding.png'),
    logo: require('../assets/images/logo.png'),
    search: require('../assets/images/search.png'),
    avatar1: require('../assets/images/avatar1.png'),
    avatar2: require('../assets/images/avatar2.png'),
    avatar3: require('../assets/images/avatar3.png'),
    avatar4: require('../assets/images/avatar4.png'),
    avatar5: require('../assets/images/avatar5.png'),
    avatar6: require('../assets/images/avatar6.png'),
    avatar7: require('../assets/images/avatar7.png'),
    avatar8: require('../assets/images/avatar8.png'),
    story_bg1: require('../assets/images/story_bg1.png'),
    story_bg2: require('../assets/images/story_bg2.png'),
    story_bg3: require('../assets/images/story_bg3.png'),
    story_bg4: require('../assets/images/story_bg4.png'),
    call_done: require('../assets/images/call_done.png'),
    call_missed: require('../assets/images/call_missed.png'),
    group: require('../assets/images/Group.png'),
    checked: require('../assets/images/checked.png'),
    beer: require('../assets/images/beer.png'),
    voice: require('../assets/images/voice.png'),
    avatar: require('../assets/images/avatar.png'),
}